{
    'name': 'OIG Contribution Management',
    'version': '1.0',
    'author': 'Echo Technology',
    'category': 'Custom',
    'summary': 'Manage agents, customers, services, and commissions.',
    'depends': ['base', 'account', 'contacts', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/agent_view.xml',
        'views/customer_view.xml',
        'views/service_view.xml',
        'views/commission_view.xml',
        'views/region_view.xml',
        'views/customer_view.xml',
        'data/sequence.xml',
        'data/customer_sequence.xml',
        'data/agent_sequence.xml',
        'data/scheduled_actions.xml',
        'reports/report_templates.xml',
    ],
    'demo': ['data/demo_data.xml'],
    'installable': True,
    'application': True,
}